name: Continuous Integration

# This action works with pull requests on protected branches
on:
  pull_request:
    branches:
      - dev
      - main
  push:
    branches:
      - puppeteer

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: install eslint
        run: npm i

      - name: run ESLint
        run: npm run lint
  
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
      
      - name: install dependencies
        run: npm i

      - name: start server and run tests
        run: npx webpack serve & sleep 5 & npm run test