name: Continuous Integration

# This action works with pull requests on protected branches and pushes
on:
  push:
  pull_request:
    branches:
      - dev
      - main

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{js,md}
      - name: install eslint
        run: npm i

      - name: run ESLint
        run: npx eslint ./js/*.js
  
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
      
      - name: install jest
        run: npm i

      - name: Unit tests
        run: npm test ./js/__testing__/unit.test.js
