name: Continuous Integration

# This action works with pull requests on protected branches
on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: install eslint
        run: npm i

      - name: run ESLint
        run: npm run lint
  
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
      
      - name: install dependencies
        run: npm i

      - name: run unit tests
        run: npm run unit-test

  puppeteer-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
      
      - name: install dependencies
        run: npm i

      - name: install live-server
        run: npm i -g live-server

      - name: start server and run tests
        run: |
          npx live-server --port=9000 source/ &

          PID=$!

          sleep 5

          echo Running tests...

          node --experimental-vm-modules node_modules/jest/bin/jest.js source/js/__testing__/puppeteer/*

          kill $PID

          fuser -k 9000/tcp

