name: Continuous Integration

# This action works with pull requests on protected branches
on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: install eslint
        run: npm i

      - name: run ESLint
        run: npx eslint ./source/js/*.js
  
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
      
      - name: install jest
        run: npm i

      - name: Unit tests
        run: npm test ./source/js/__testing__/unit.test.js
