name: Styling and Documentation
on: 
    push:
      branches:
        - dev
      paths:
        - '**/*.js'
    workflow_dispatch:

jobs:
    styling-and-documentation:
      if: ${{ github.actor != 'cse110-sp24-group4-bot' }}
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
          # Make sure the actual branch is checked out when running on pull requests
            token: ${{ secrets.AUTOMATION_BOT }}
            ref: ${{ github.head_ref }}

        - name: Install Dependencies
          run: npm i
        
        - name: Prettify code
          run: npm run prettier
        
        - name: Generate JSDoc
          run: npm run generate-docs
        
        - name: Commit changes
          run: |
            git config --local user.email "action@github.com"
            git config --local user.name "Github Action"
            git add .
            git commit -m "prettify code and generate jsdoc"
        
        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.AUTOMATION_BOT }}
            branch: ${{ github.ref }}