name: Styling and Documentation
on: 
    push:
      branches:
        - dev
      paths:
        - '**/*.js'
    workflow_dispatch:

jobs:
    prettier:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            # Make sure the actual branch is checked out when running on pull requests
            ref: ${{ github.head_ref }}

        - name: Prettify code
          uses: creyD/prettier_action@v4.3
          with:
            prettier_options: --write **/*.{js,md}
    
    jsdoc-job:
        runs-on: ubuntu-latest
        steps:
          - name: Get access to repo
            uses: actions/checkout@v4
          - name: Install Dependencies
            run: |
                npm install
                npm install jsdoc docdash
          - name: Generate JSDoc
            run: npx jsdoc -c ./jsdoc.json
          - name: Commit JSDoc
            if: ${{ github.actor != 'github-actions' }}
            run: |
                git config --local user.email "action@github.com"
                git config --local user.name "GitHub Action"
                git add .
                git commit -m "Generate JSDoc"
          - name: Push JSDoc
            if: ${{ github.actor != 'github-actions' }}
            uses: ad-m/github-push-action@master
            with:
               github_token: ${{secrets.GITHUB_TOKEN}}
               branch: ${{ github.ref }}